language: cpp
sudo: required
dist: trusty
group: deprecated-2017Q4
compiler:
- g++
os: 
- linux
before_install:
    - sudo apt-get install cmake
    - cmake --version

script: cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=./ && cmake --build ./ --config release --target install
