before_install:
    - sudo apt-get install cmake
    - sudo apt-get upgrade
language: cpp
script: cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=./ && cmake --build ./ --config release --target install
